sudo: required
language: python
dist: trusty
services:
- docker
before_script:
- docker --version
- docker-compose --version
script:
- docker-compose build
- docker images
- docker-compose up -d
- docker ps
- sleep 10
- chmod ugo+x tests/test_java.sh && bash tests/test_java.sh
- chmod ugo+x tests/test_kafka.sh && bash tests/test_kafka.sh
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push vietdien2005/kafka_docker
env:
  matrix:
  - secure: bxEXD6g5QPoPvCeWfg5DWtGouLrbFHm4DHKic863SFK4j/eRmlUyHEm56vysUtRDD6vfA7jwHiNLXrQaG/JbPZF7NzKELCoCL0bAWKuWi0xCWF+e7YMkDahUcQCRHliqoQ+AhNCYVWdik7xctSkX/+tsFrRNtAsxuPIAqh7SdMzSbFuashGcEoFK6x6aHZUJft1w/iaZ4UesS1Y7As7J3+eKV8D1ezb8FldErziozPZfaTPFiXczc7Uo0nrF+trZ4cq4KhhSGJy8hGQN3DtjnyE49SQOHdONRlKE4dKL/s42Jx5S/N6/RHiz3RciKV+nEEeQ150+C+t6KZeJgT1bzru7pxzAmi3N0JEDLNkhIzV1OUqgtPg+gY1iS1edLDnA9OK8BihXjUj8RZiFN2KVqGFeYWLK4nEmjsL60NMl7bw8VHYrfxRpOTNXc5ovyxUQalzfQN5U202Eae+rO7o/A4cpYu370sQiFYt21DzpSkjTfDG0zTjiwSFWwLMlgjTCswxo2Y1VzDAG5wzEopqe5ECzA0ePZy/xu5UqOR2KeX7mmUIF8jqlYTcOyNAcEFvQih2mHVqo26Y0NB0bASTF5kLTj3PDAsXnKngB5QJK8zCCJ/5LY6bucC3KAN22Fqkrt7yadCqil9jx65ey+Uryj3MwUWsboEZePPoxlIRWX14=
  - secure: EQEGbV4/yOfA02R0L5YGVGtAaRSXeAH6P0FQG+KmD+ufcDa1wQq4RKYX05/UrTWQje29oRFm0ceNSyLC7Q31wJhrWnKWlv2Jw8jX/Fr0pjEIHEViHm5Q69BjgGJAx3Je9OPjfOXgRGUEBhjXE/4I2ctiAXpDV6TPGSw/f5EX0DRusjIssv2Hfd+sqTbQci2GSwQWxMuGgGhdRl1z5YgXerIGifiDaRaKQEeNpJZsadU9B3PgyHDDYCds/Y+Kpfv+islBRot3miZYHtJRWH3Fqtg5fc1oYxClMy2WPHZjSwksClQLooMefX1L3eYgDf/pMOUtv+0pe70k5FyJymrorPbK191Ds4voOpeRzXZqtRy9AKVR5l1LuEVxJKtnFPgATAVMs1RiqtJgQ6fg6ez7z2oCeYiZTRbkG2trtfbDiLssj89mb1J+hhU/SUGaq9crQAgAk95DAUxVJ0Oju3tcP9Na+8KORHLHhQdKBzRy+7h1vC1n8Kj8BLnT2m0QuSP1cGyMEO9+DhP6v7oN7kcgL0k9mXPxGIcyVUgKSsTEfkjavKJy/+fzhSkBiLeIM7hepkS/s/74iFxsDF6gm4Nqs52Eu6vptVtNdv2E6IfBM1ATIq13QRLN3mrEro02ObCgVm/nrS2ROUb6sKXWNJopxPLWrsAkwRlNKWpdTUhkR2Q=
  - secure: CC35PC4ul91FiSCM6KZa/fKqTt78Jx4vF1UhSbIHW4iyJInmv/V/+OLe/FaTERzGK1QylkQRKq9RhInBYynKuMqiupa1iJ2poFnFx8fGJz/g3H/1DFDPMCxCQtumIvFuigc0+YGA5WVDcVEWvxay5m/F4ZRl7vKpAvyHhsyoILVbYXVklxv62DibW2xkJFRAvUCZAHGdPQOJT45Mg1lP3yejQ+8IuDG6dpVDbbqe9D6u+RAOE4Z/o++/XxRI/st4IjRtSnMptOCBVq089qinqdxiU4/4ijC1t97VEYlWH9zJz2u9VNDzARTrwF/OYK1Y4yoMtmSraGlOpp2BNj8Ng1u85mRwHHSXkGTVEkhpXM0iYmdixtXLsDas5A+pNR4wGfzebfhC3JN+CMroh0tfEXVL2aJhfc330Pk9oORUXCaDWvaM6A1z+DJOC+64+JehLbYbcduxlA9JgSti+cPWhn9xeZEopacSCFq4UJEpOtyV8zfnU9jkb9P/Mzu37GY1QH/3L4YhJfRrUogTRaIkMxsg8j5cqHjc39adABKJXdwChbIBAbrnBZBuYZHbdaMhfPklT6eK6+nV9ZKXqC2/EMHewGOWPvof/RHqQZ69oGTk23XiSR61Djofq1/ErCBYNNP2xDDKqv9UDMaVVf8XNVBKTcRFcuQByx89sg8POpE=
