sudo: required
language: python
dist: trusty
services:
- docker
before_script:
- docker --version
- docker-compose --version
- pip install kafka-python
script:
- docker-compose build
- docker images
- docker-compose up -d
- docker ps
- sleep 10
- chmod ugo+x tests/test_java.sh && bash tests/test_java.sh
- chmod ugo+x tests/test_kafka.sh && bash tests/test_kafka.sh
# - python tests/python_kafka.py
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=vietdien2005/kafka_docker
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
env:
  global:
  - secure: bqWkuwDhCnLyfTC7O8jycGlUjY8VWAqb9D1MdzzEeSMUg8iOO++Ogg5H/i0vQ01i9ebKxSyq9om3vDYzHGDiORSpHH/L7B5KZbaDMdtLOcYG6OzcXCIVILbFaPuggTVqkBbpbR3RZ9+8E+dywVqCHLXtOqP00yGYrND9BbD1jjMPVpc6+EYEhaedf+Sw1kdDMej5lMxOAZk07jQAMU5e1pcjImsw1pPi5yxJswvWOhlvpcxEzvz3RRkKtUBoaQqk58GLTEY9Mgqiqj5VVU6EZw/NFkAfK0acQ5shuCBfELHyRr0B/Sd+sFfgIyji/FIzaDbCb5S2B+fWpAnRpi6E1SeTqHXQzRJuCNr7OOpFr6FouE23CNvzC1uPINLrf+irhd1ZYGesEI+qdqe3XC/UxK16tXqsv8gAJcK5ouGxpMZGpXfjwjCqSVXIvVyLJlHzD/GCnrvm3LAwSezwzoubAflOl17bRdYH1nPTze4sJBEySUGLycCL5oxqPyo7iCzusFgEY578ulkGsvLZOaUbwS/d3gE/7edciqJNTGCMUIGuEEgc4U9yniVskTm16L4e+b4bVtr0MY52PdrzgZwNAyUGXqR+NqkeaM9k7uTOtDZH6S08Nv+78YqalUV2wGF3EIobL1Dzpw7oCfDGfHzAAWOs7Y3gJqiTgNgwzsEjjUo=
  - secure: KaCdWcUWZojHvCvARqhdLgZOzJU90l9salS+Xh7pIYTbjjWFGJp9db/DXMqIZzLJDz0wZPb/nvns2SwRQX0kCxVFj9LL3FppDu1UqZSWgO6+fArXsTbMbTwD2zk5hxNBOb2ozNbiFDt8EvonV/+dFWro0ostIxmyw2juX6RrEdl9H4EZpQA53VysTtc2dnwQ5Pa27qjcjcWhXuViM9RJOmq+z4LgFzgYuVlQvRoOns0sBL+aN2p4Stxjp18MXKUjX2URvqWAkxjyhvDBmqIGkiXn7rXkZ8xuujUHkyP0mExQ+UJEGovmr5VBmcfrnPhUV82T3clyWAQkBJFDNGhMmbhgMVe2zkpw3nVeD0KaAD7lu/gjuze8+Mp2gesCbhf3sht9gHIOcK+XsBCOSZMNFSM41FXxdtKDIdrNvHBcAsifMh1W6DMeg0mvUXt8IzegQ8/ZXqn8M11mUMkkzBNg4daZyhtKGDY4CiXfG5Y2nnHdN/nLAmNDYSu4h3UWnE1ID6CKjovZY2D2H/3Marh8tRlgHmKfjUfXjL8jabeWGwtrt8lOe1SgHhp4xFSLM8StEYV7ilJ/6mjZa6AfEABagJ2FueHKV0VII0oqE0l8MmZpikcahAhATqgslVpLhJO4gio8fna8dViy4yLblWdkX2PCKTDe32uxvl8SemP2gks=
