version: "3"

services:

    zookeeper:
        container_name: zookeeper
        image: zookeeper:latest
        ports:
            - 2181

    kafka:
        container_name: kafka
        build: 
            context: ./
        image: vietdien2005/kafka-docker-alpine:latest
        command: kafka-server-start.sh config/server.properties
        depends_on:
            - zookeeper
        ports:
            - 9092
        links:
            - zookeeper
      