version: "3"

services:

    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - "2181:2181"

    kafka:
        container_name: kafka
        build:
            context: ./
        image: vietdien2005/kafka-docker-alpine:latest
        ports:
            - "9092:9092"
        links:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

